unpack.sh
This should make the catkin build successful as long as `unpack.sh` is run first.
=> Update unpack.sh to init git submodules for uavcan_dsdl repo

spear_simulator/models/rover/TARS_V2.urdf
Gazebo sensor plugins need to be associated with a link in the urdf so I added a link called "imu_link" which the gazebo plugin can reference. Now it should publish to the "/imu" ros topic.
=> Add imu_link to urdf

spear_rover/launch/state_estimate.launch
ROS doesn't like it when there are tabs at the beginning of a line in a rosparam block so I replaced them with spaces. Also fixed syntax for some xml ending tags.
=> Fix syntax errors in state_estimate.launch

spear_rover/package.xml
In the future, whenever you need a new package, could you add it to the package.xml file?
It means that someone can just run a rosdep command to get all the things they need, instead of hunting stuff down in READMEs.
=> Added robot_localization to spear_rover dependancies.

spear_rover/CMakeLists.txt, spear_rover/nodes/move_with_twist.py
The node is spear_rover/move_with_twist.py. It accepts two arguments:
- action: one of "forward", "reverse", "left", or "right" (defaults to "forward")
- duration: number of seconds to send twist messages (defaults to 5)
=> Add a node for moving via twist messages

spear-env.Dockerfile, spear_simulator/package.xml
Earlier I put the gazebo gps and imu dependencies in the dockerfile. This commit fixes that.
=> Move dependencies to xml

.gitignore, README.md, build.bash, run-docker.bash, unpack.sh
We now:
- Copy everything from /opt/ros and /root/ros/devel/include to
/tmp/.docker-opt-ros-mount and /tmp/.docker-root-ros-include-mount,
respectively, on each build
- Mount those two folders from the container's /tmp directory to the
host using docker volumes
- Use sed to modify the generated compile_commands.json to point to the
host machine mount points
This allows tools like Vim's YouCompleteMe, or really anything that
recognizes the standard compile_commands.json format, to find most of
the C++ headers required for code autocompletion.
Notable things that don't work:
- Anything that imports ros message types, as catkin does some sort of
voodoo black magic header generation and I can't find their location on
the file system.
- Anything that uses a system-wide C++ library that isn't …
=> Get *most* C++ autocompletion working

spear-env.Dockerfile
Some people's docker images won't build when you use sudo commands in a Dockerfile. For some reason the travis build was still passing.
=> Remove sudo command from spear-env.Dockerfile

Dockerfile
Because I'm tired of typing `cd software` every single time I start the container.
=> Set working dir to /software in Dockerfile

spear_simulator/models/rover/TARS_V2.urdf
This commit removes the ZED camera model in camera_link in gazebo. We can add it back in later if we need to.
=> Fixed the simulator rover model so that it shows in the simulator

Dockerfile, unpack.sh
Downloading the gazebo model database used to be in unpack.sh. Some of the simulator worlds use assets from that database, which are downloaded at runtime as needed. Downloading them all in unpack.sh was meant to trade that runtime penalty for a longer build time.
But everything in unpack.sh is always re-run whenever the docker image is rebuilt (it happens after the COPY and so has no caching). So, this PR moves the download into the Dockerfile so it can be cached.
The disadvantage here is there is no longer a check if we're in "dev" mode to download the models, so they will also be in the rover's docker image and take up space. But since we don't actually have a good way to build the rover's version of the image (short of manually editing `docker-compose.yml`), this doesn't seem like …
=> Move download model database into dockerfile

build.bash
I accidentally broke code completion by moving to `catkin build` (since it doesn't produce a single `compile_commands.json` file to be copied). This fixes that by merging the individual `compile_commands.json` files into one before copying it.
=> Fix code completion

Dockerfile
OSRF moved the repo from bitbucket to github, so this updates the Dockerfile to use the correct url.
=> Update gazebo model database url

spear_rover/config/controllers.yaml
The arm controller parameters had a `gains` parameter. This is not used with position controllers (and the arm seems to function fine without it), so I removed the parameter.
=> Remove gains from arm controller parameters

Dockerfile, spear_rover/CMakeLists.txt, spear_rover/nodes/arm_ik.py, spear_rover/rviz/drive.rviz, spear_rover/rviz/navigate.rviz, spear_simulator/models/rover/arm.urdf.xacro
Adds a node which illustrates the use of ikpy to move the arm. Also changes the transform of `arm_mount` to get rid of an ik singularity when the arm is facing forward (now it happens when the arm is facing backward, which should not be a problem).
Right now the demo doesn't use `moveit` at all. The disadvantage is that `ikpy` doesn't know about self-collisions or constraints. The advantage is it doesn't need the massive amount of configuration that moveit does (that configuration is already done, but it would be kind of nice to remove it to make the code easier to understand).
An alternate approach would be to use `ikpy` to generate arm angles, and then pass those to `moveit` as a target.
=> Add demo IK node

unpack.sh
This package is a depedency for canros.
I recently got the following error when trying to run `docker-compose` build on my machine:
```
_______________________________________________________________________________
Errors << canros:cmake /root/ros/logs/canros/build.cmake.000.log               
The package 'monotonic' is not available, the library will use real time instead of monotonic time.
This implies that the library may misbehave if system clock is adjusted while the library is running.
In order to fix this problem, consider either option:
1. Switch to Python 3.
2. Install the missing package, e.g. using pip:
pip install monotonic
Traceback (most recent call last):
File "/root/ros/src/canros/scripts/generate.py", line 18, in <module>
import canros
File …
```
=> Add installation of python package `monotonic` in unpack.sh

Dockerfile
The next version of ikpy drops support for Python 2. Until we upgrade to ros noetic or foxy we need to use an older version of ikpy.
=> Fix ikpy verson at 3.0.1

Dockerfile, spear_rover/launch/station_adapter.launch, spear_rover/package.xml
For #223 , which basically already done, but this is a way to get full-sized images instead of the lower-quality ones streamed to the station.
=> Run image_saver in station adapter launch file

catkin_lint.bash, spear_rover/config/controllers.yaml, spear_simulator/models/rover/arm.urdf.xacro, spear_simulator/package.xml, unpack.sh
This is not polished, but it adds a gripper to the arm. The gripper is controlled via the _grab_ joint. Depending on the gears used in the actual robot, the amount _grab_ turns will have to be scaled when turning the real gripper control motor. This could be done in firmware or potentially by adding a transmission to the gazebo model.
=> Add gripper to arm

.gitmodules, spear_rover/libcanard, spear_rover/uavcan_dsdl
This keeps things organized, and I want to be able to move around package locations without having to worry about using `git mv`.
=> Move submodules to their own directory

pkg/spear_planner/CMakeLists.txt, pkg/spear_planner/package.xml, pkg/spear_planner/python/spear_planner/history.py, pkg/spear_planner/python/spear_planner/test_history.py, pkg/spear_planner/setup.py, spear_rover/libcanard, spear_rover/uavcan_dsdl
If we want to be able to switch between autonomous and manual operation in competition, it might be useful to have a way to start the state machine from an arbitrary state. This PR adds a subclass to do that, and another class to save the state machine history as it operates.
Contains the changes from #258 which should be merged first.
=> Add a way to save and restore state machine 

pkg/spear_simulator/models/rover/TARS_V2.urdf.xacro, pkg/spear_simulator/models/rover/constants.xacro, pkg/spear_simulator/models/rover/materials.xacro, pkg/spear_simulator/models/rover/webcam.urdf.xacro, pkg/spear_simulator/models/rover/wheel.urdf.xacro, pkg/spear_simulator/models/rover/zed_cam.urdf.xacro, scripts/unpack.sh
- Adds webcams at the front, back, left, and right of the rover
- Moves the ZED camera stuff into its own xacro file
- Uses the ZED camera stl model from zed-ros-wrapper to show the ZED camera in gazebo/rviz
Currently webcams publish to `/webcam_front`, `/webcam_back`, etc. Not sure if this is the right choice, but it's pretty easy to change if necessary.
=> Split cameras into separate files and add webcams

pkg/spear_simulator/launch/rover.launch, pkg/spear_simulator/models/mars-12k/model.config, pkg/spear_simulator/models/mars-12k/model.sdf, pkg/spear_simulator/models/mars-2k/model.config, pkg/spear_simulator/models/mars-2k/model.sdf, pkg/spear_simulator/models/mars-4k/model.config, pkg/spear_simulator/models/mars-4k/model.sdf, pkg/spear_simulator/worlds/mars/mars-12k.world, pkg/spear_simulator/worlds/mars/mars-2k.world, pkg/spear_simulator/worlds/mars/mars-4k.world
Adds worlds with 2k, 4k, and 12k mars textures (the heightmap has nothing to do with Mars though, it's just a default terrain heightmap that comes with gazebo). Only the 2k texture is committed to source control; the others can be downloaded from google drive if necessary. Also sets the 2k mars world as the default.
There's an annoying issue here (which was likely responsible for several of the previous attempts to do this failing) where gazebo keeps a terrain texture cache that uses the terrain heights, but nothing else, as a key. So I had to vary the terrain heights slightly among the Mars models to make the textures load correctly.
=> Add worlds with Mars texture

pkg/spear_rover/src/hardware.cpp
This has a number of advantages
- It's robust against missed odometry messages
- It matches the fields in `actuator.Status`
- It limits data transformations at lower abstraction layers (no more accumulation at the hardware interface layer)
...of course it's all academic anyway since we aren't going to have wheel odometry at circ.
Contains the changes from #278 which will have to be merged first.
=> Use (angular) position from wheel odometry instead of delta

pkg/spear_station/launch/flexbe.launch, pkg/spear_station/package.xml, scripts/catkin_lint.bash
I was getting the following error when trying to build the docker image:
ERROR: the following rosdeps failed to install
apt: command [apt-get install -y ros-melodic-flexbe-app] failed
apt: Failed to detect successful installation of [ros-melodic-flexbe-app]
This allows the docker build to succeed. We won't be using flexbe for this competition
=> Remove flexbe_app dependency
