UofA-SPEAR/software

.travis.yml
Dockerfile
spear_msgs/msg/WheelCmdArray.msg
spear_rover/CMakeLists.txt
spear_rover/src/arm_ik.cpp
spear_rover/src/arm_verifier.cpp
spear_rover/src/ball_detector.cpp
spear_rover/src/ball_drawer.cpp
spear_rover/src/hardware_interface.cpp
spear_simulator/generate_balls.py
spear_station/nodes/arm.py
spear_station/nodes/drive.py
spear_station/nodes/knob.py
spear_station/python/spear_station/ros_station.py
unpack.sh

Fixed some includes of message types in cpp files. Used hacky fix to make unpack.sh work

Unpack ryan

---

README.md

Add more detailed setup instructions to the README. This is in an effort to move all setup instructions to one place

Readme instructions ryan

---

unpack.sh

Add section in unpack.sh to GAZEBO_MODEL_PATH

---

spear_rover/launch/ball_test.launch
spear_rover/launch/cam.launch
spear_rover/launch/rover2_can.launch
spear_rover/launch/rover2_vcan.launch

Some of the launch files in spear_rover still had the old package names

Update launch files in spear_rover to find the spear_rover package

---

spear_simulator/launch/gazebo.launch
spear_simulator/models/rover/TARS_V2.urdf

Add depth camera sensor to urdf which publishes to /camera/depth and /camera/rgb topics. These topics can be viewed in rviz.

Gazebo cam ryan

---

spear_simulator/launch/diffdrive.launch

This launches an rtabmap node which subscribes to depth camera messages from gazebo.

Rtabmap simulator ryan

---

README.md

Add note that we are using python 3.5

Update main readme with info on python linting

---

spear_rover/CMakeLists.txt
spear_rover/include/skidsteer.hpp
spear_rover/nodes/mapper.py
spear_rover/src/odom_tf_publisher.cpp
spear_rover/src/test_wheel_odom_publisher.cpp
spear_rover/src/twist_to_skidsteer.cpp

Created a node to publish transform from "base_link" to "odom".
Also created a node to convert geometry_msgs/Twist messages to canros ArrayCommand messages.

Implement skid steer odometry

---

README.md
spear_rover/package.xml
spear_simulator/package.xml
unpack.sh

Just adding some dependancy stuff.

Package dependancies david

---

spear_rover/config/razor_calibration.yaml
spear_rover/launch/sensors.launch
spear_rover/package.xml

Added razor imu config stuff and a sensors launch file

Sensors launch david

---

unpack.sh

I just want this to be something I can tell people verbally and not have to go to a website to find the command. Feel free to kebosh this if something is wrong.

Added update_rosdeps alias to make dependencies easier

---

mission-planner-gui/example-actions
mission-planner-gui/src/make_state.js

Added a mission planner command for relative motion with yaw angle, and commands for moving forward, and turning left/right.

Add rotation commands to augment relative movement

---

spear_rover/launch/sensors.launch

sensor_msgs.launch now launches rosbag to record gps fix

Run rosbag to record gps fix

---

README.md

The docker package installs the wrong stuff.

Ubuntu installation instructions were incorrect

---

Dockerfile
README.md
run-docker.bash
spear-env.Dockerfile
spear_rover/CMakeLists.txt
spear_rover/package.xml
spear_simulator/package.xml
unpack.sh

Get a simple docker setup with x11 forwarding and volumes

simple docker setup

---

spear-env.Dockerfile
spear_simulator/launch/diffdrive.launch
spear_simulator/rviz/diffdrive.rviz

The hector gazebo plugins weren't installed in the docker image, so the gps in gazebo was failing silently. Fixed now.

Fix gps and imu in simulation

---

spear_rover/config/ekf/ekf_common.yaml
spear_rover/config/ekf/ekf_map.yaml
spear_rover/launch/state_estimate.launch
spear_simulator/launch/nav.launch

Move the configuration for the EKFs to some yaml files which are easier to edit (and removes the need to repeat configuration).

Clean up ekf config

---

run-docker.bash

This is useful when attaching to the container

Set container name in run-docker.bash

---

README.md
Vagrantfile

Use vagrant for VMs

---

spear_rover/setup-can.bash
spear_rover/setup-vcan.bash
spear_rover/vcan-setup.bash

Developed after way too many hours of oscilloscope probing, googling,
and generally being annoyed.
Docs are being added to the wiki.
Does not work from within docker yet - need to add the capability to the
container through docker-compose.

Add improved scripts for setting up the CAN interface

---

unpack.sh

In unpack.sh, clones the repos we need in parallel, hopefully speeding up unpack time a little

Parallelize repo cloning in unpack.sh

---

pkg/spear_simulator/nodes.md
pkg/spear_simulator/nodes/dosimeter_dummy_node.py

This node generates fake dosimeter readings. This should be useful for testing purposes while implementing #265

Add dummy dosimeter node

---

pkg/spear_planner/nodes/state_machine.py

It doesn't use the fancy history thing from earlier, but I needed something done quickly and I'm still not sure if/how I want to use the history thing anyway...

Add demo node with demo statemachine to spear_planner

---

Dockerfile
pkg/spear_planner/nodes/state_machine.py
pkg/spear_planner/python/spear_planner/test_history.py
pkg/spear_planner/setup.py
pkg/spear_rover/nodes/diagnostics.py
pkg/spear_rover/nodes/move_with_twist.py
pkg/spear_rover/nodes/ocr.py
pkg/spear_rover/setup.py
pkg/spear_simulator/nodes/dosimeter_dummy_node.py
pkg/spear_station/nodes/arm_ik.py
pkg/spear_station/setup.py
pkg/spear_util/setup.py
pkg/tests/nodes/test_drive_sim.py
scripts/catkin_lint.bash
scripts/unpack.sh
scripts/xml_lint.bash

This probably breaks a LOT of things (e.g. CAN) but it's necessary at the moment since the tx2 doesn't support noetic.
CAN will be fixed in the next PR.

Downgrade to ros melodic
